apiVersion: apps/v1
kind: Deployment
metadata:
  name: dquiz-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dquiz-frontend
  template:
    metadata:
      labels:
        app: dquiz-frontend
    spec:
      containers:
        - name: dquiz-frontend
          image: deviliam/dquiz-frontend:v27
          ports:
            - containerPort: 80
