name: Build and Push Docker Images

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:

  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend_changed: ${{ steps.filter.outputs.frontend }}
      backend_changed: ${{ steps.filter.outputs.backend }}
      VERSION: ${{ steps.version.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Detect changes in folders
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - "frontend/**"
            backend:
              - "backend/**"

      - name: Generate Auto Version Tag
        id: version
        run: echo "version=v${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT
        # Auto creates v1 → v2 → v3 ...


  build-frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Login GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USER }}" --password-stdin

      - name: Build + Push Frontend (DockerHub + GHCR)
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          VERSION=${{ needs.detect-changes.outputs.VERSION }}

          # -------- Build Image --------
          docker build -t deviliam/dquiz-frontend:${VERSION} \
                       -t deviliam/dquiz-frontend:sha-${SHORT_SHA} \
                       -t deviliam/dquiz-frontend:latest ./frontend

          # -------- Push to DockerHub --------
          docker push deviliam/dquiz-frontend:${VERSION}
          docker push deviliam/dquiz-frontend:sha-${SHORT_SHA}
          docker push deviliam/dquiz-frontend:latest

          # -------- Tag for GHCR --------
          docker tag deviliam/dquiz-frontend:${VERSION} ghcr.io/deviliam/dquiz-frontend:${VERSION}
          docker tag deviliam/dquiz-frontend:sha-${SHORT_SHA} ghcr.io/deviliam/dquiz-frontend:sha-${SHORT_SHA}
          docker tag deviliam/dquiz-frontend:latest ghcr.io/deviliam/dquiz-frontend:latest

          # -------- Push to GHCR --------
          docker push ghcr.io/deviliam/dquiz-frontend:${VERSION}
          docker push ghcr.io/deviliam/dquiz-frontend:sha-${SHORT_SHA}
          docker push ghcr.io/deviliam/dquiz-frontend:latest



  build-backend:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Login GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USER }}" --password-stdin

      - name: Build + Push Backend (DockerHub + GHCR)
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          VERSION=${{ needs.detect-changes.outputs.VERSION }}

          # -------- Build --------
          docker build -t deviliam/dquiz-backend:${VERSION} \
                       -t deviliam/dquiz-backend:sha-${SHORT_SHA} \
                       -t deviliam/dquiz-backend:latest ./backend

          # -------- Push to DockerHub --------
          docker push deviliam/dquiz-backend:${VERSION}
          docker push deviliam/dquiz-backend:sha-${SHORT_SHA}
          docker push deviliam/dquiz-backend:latest

          # -------- Tag for GHCR --------
          docker tag deviliam/dquiz-backend:${VERSION} ghcr.io/deviliam/dquiz-backend:${VERSION}
          docker tag deviliam/dquiz-backend:sha-${SHORT_SHA} ghcr.io/deviliam/dquiz-backend:sha-${SHORT_SHA}
          docker tag deviliam/dquiz-backend:latest ghcr.io/deviliam/dquiz-backend:latest

          # -------- Push to GHCR --------
          docker push ghcr.io/deviliam/dquiz-backend:${VERSION}
          docker push ghcr.io/deviliam/dquiz-backend:sha-${SHORT_SHA}
          docker push ghcr.io/deviliam/dquiz-backend:latest
