name: Build and Push Docker Images

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  FRONTEND_IMAGE: deviliam/dquiz-frontend
  BACKEND_IMAGE: deviliam/dquiz-backend

jobs:

  build-frontend:
    name: Build Frontend Image
    if: |
      contains(join(github.event.commits.*.added, ' '), 'frontend/') ||
      contains(join(github.event.commits.*.modified, ' '), 'frontend/') ||
      contains(join(github.event.commits.*.removed, ' '), 'frontend/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set SHORT_SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Build & Push Frontend
        run: |
          docker build -t $FRONTEND_IMAGE:latest -t $FRONTEND_IMAGE:${SHORT_SHA} ./frontend
          docker push $FRONTEND_IMAGE:latest
          docker push $FRONTEND_IMAGE:${SHORT_SHA}


  build-backend:
    name: Build Backend Image
    if: |
      contains(join(github.event.commits.*.added, ' '), 'backend/') ||
      contains(join(github.event.commits.*.modified, ' '), 'backend/') ||
      contains(join(github.event.commits.*.removed, ' '), 'backend/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set SHORT_SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Build & Push Backend
        run: |
          docker build -t $BACKEND_IMAGE:latest -t $BACKEND_IMAGE:${SHORT_SHA} ./backend
          docker push $BACKEND_IMAGE:latest
          docker push $BACKEND_IMAGE:${SHORT_SHA}
