name: Build and Push Docker Images

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  FRONTEND_IMAGE: devil/dquiz-frontend
  BACKEND_IMAGE: devil/dquiz-backend

jobs:

  build-frontend:
    name: Build Frontend Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set SHORT_SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
        # takes first 7 characters from commit SHA and exports as env var SHORT_SHA

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin
        # logs in to Docker Hub using GitHub Secrets

      - name: Build & Push Frontend
        run: |
          docker build -t $FRONTEND_IMAGE:latest -t $FRONTEND_IMAGE:$SHORT_SHA ./frontend
          docker push $FRONTEND_IMAGE:latest
          docker push $FRONTEND_IMAGE:$SHORT_SHA
        # builds frontend image with tags :latest and :<short_sha> and pushes both


  build-backend:
    name: Build Backend Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set SHORT_SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
        # same SHORT_SHA for backend, based on same commit

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin
        # logs in to Docker Hub using GitHub Secrets

      - name: Build & Push Backend
        run: |
          docker build -t $BACKEND_IMAGE:latest -t $BACKEND_IMAGE:$SHORT_SHA ./backend
          docker push $BACKEND_IMAGE:latest
          docker push $BACKEND_IMAGE:$SHORT_SHA
        # builds backend image with tags :latest and :<short_sha> and pushes both
