name: Build and Push Docker Images

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:

  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend_changed: ${{ steps.filter.outputs.frontend }}
      backend_changed: ${{ steps.filter.outputs.backend }}
      VERSION: ${{ steps.version.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Detect changes in folders
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - "frontend/**"
            backend:
              - "backend/**"

      - name: Generate Auto Version Tag
        id: version
        run: echo "version=v${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT


  build-frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Login to GHCR (Correct FIX)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build + Push Frontend (DockerHub + GHCR)
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          VERSION=${{ needs.detect-changes.outputs.VERSION }}

          docker build -t deviliam/dquiz-frontend:${VERSION} \
                       -t deviliam/dquiz-frontend:sha-${SHORT_SHA} \
                       -t deviliam/dquiz-frontend:latest ./frontend

          docker push deviliam/dquiz-frontend:${VERSION}
          docker push deviliam/dquiz-frontend:sha-${SHORT_SHA}
          docker push deviliam/dquiz-frontend:latest

          docker tag deviliam/dquiz-frontend:${VERSION} ghcr.io/deviliam/dquiz-frontend:${VERSION}
          docker tag deviliam/dquiz-frontend:sha-${SHORT_SHA} ghcr.io/deviliam/dquiz-frontend:sha-${SHORT_SHA}
          docker tag deviliam/dquiz-frontend:latest ghcr.io/deviliam/dquiz-frontend:latest

          docker push ghcr.io/deviliam/dquiz-frontend:${VERSION}
          docker push ghcr.io/deviliam/dquiz-frontend:sha-${SHORT_SHA}
          docker push ghcr.io/deviliam/dquiz-frontend:latest


  build-backend:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Login to GHCR (Correct FIX)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build + Push Backend (DockerHub + GHCR)
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          VERSION=${{ needs.detect-changes.outputs.VERSION }}

          docker build -t deviliam/dquiz-backend:${VERSION} \
                       -t deviliam/dquiz-backend:sha-${SHORT_SHA} \
                       -t deviliam/dquiz-backend:latest ./backend

          docker push deviliam/dquiz-backend:${VERSION}
          docker push deviliam/dquiz-backend:sha-${SHORT_SHA}
          docker push deviliam/dquiz-backend:latest

          docker tag deviliam/dquiz-backend:${VERSION} ghcr.io/deviliam/dquiz-backend:${VERSION}
          docker tag deviliam/dquiz-backend:sha-${SHORT_SHA} ghcr.io/deviliam/dquiz-backend:sha-${SHORT_SHA}
          docker tag deviliam/dquiz-backend:latest ghcr.io/deviliam/dquiz-backend:latest

          docker push ghcr.io/deviliam/dquiz-backend:${VERSION}
          docker push ghcr.io/deviliam/dquiz-backend:sha-${SHORT_SHA}
          docker push ghcr.io/deviliam/dquiz-backend:latest
